import { Restaurant, Address, Order, User } from '../types';

export const MOCK_USER: User = {
  id: 'usr_1',
  email: 'alex.smith@example.com',
  phone: '+1 (555) 019-2834',
  firstName: 'Alex',
  lastName: 'Smith',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
};

export const MOCK_ADDRESSES: Address[] = [
  {
    id: 'adr_1',
    title: 'Home',
    addressLine1: '128 Orchard St',
    addressLine2: 'Apt 4B',
    city: 'New York',
    state: 'NY',
    postalCode: '10002',
    country: 'USA',
    latitude: 40.7203,
    longitude: -73.9892,
    isDefault: true,
  },
  {
    id: 'adr_2',
    title: 'Office',
    addressLine1: '350 5th Ave',
    addressLine2: 'Floor 64',
    city: 'New York',
    state: 'NY',
    postalCode: '10118',
    country: 'USA',
    latitude: 40.7484,
    longitude: -73.9857,
    isDefault: false,
  },
];

export const MOCK_CATEGORIES = [
  { id: 'cat_1', name: 'Pizza', icon: '🍕' },
  { id: 'cat_2', name: 'Burgers', icon: '🍔' },
  { id: 'cat_3', name: 'Sushi', icon: '🍣' },
  { id: 'cat_4', name: 'Salads', icon: '🥗' },
  { id: 'cat_5', name: 'Desserts', icon: '🍰' },
  { id: 'cat_6', name: 'Drinks', icon: '🥤' },
  { id: 'cat_7', name: 'Asian', icon: '🍜' },
  { id: 'cat_8', name: 'Mexican', icon: '🌮' },
];

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'res_1',
    name: 'Tavern & Pizzeria',
    description: 'Neapolitan style wood-fired pizzas with artisanal toppings.',
    address: '84 Rivington St, New York, NY 10002',
    latitude: 40.7209,
    longitude: -73.9881,
    logoUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=150&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    phoneNumber: '+1 (555) 234-5678',
    rating: 4.8,
    reviewCount: 342,
    isFeatured: true,
    deliveryRadiusKm: 4.0,
    minOrderAmount: 15.00,
    baseDeliveryFee: 2.99,
    prepTimeRange: '15-25 min',
    categories: ['Pizza', 'Italian'],
    distanceKm: 0.8,
    promoTag: 'Buy 1 Get 1 Free',
    foodItems: [
      {
        id: 'food_1',
        restaurantId: 'res_1',
        name: 'Margherita Pizza',
        description: 'San Marzano tomatoes, fresh mozzarella, fresh basil, and extra virgin olive oil.',
        price: 14.99,
        imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isEgg: false,
        isNonVeg: false,
        isAvailable: true,
        rating: 4.9,
        variants: [
          { id: 'v_1', name: 'Personal 10"', price: 14.99, isAvailable: true },
          { id: 'v_2', name: 'Large 14"', price: 19.99, isAvailable: true },
        ],
        addonGroups: [
          {
            id: 'ag_1',
            name: 'Extra Toppings',
            minSelections: 0,
            maxSelections: 4,
            isRequired: false,
            items: [
              { id: 'add_1', name: 'Pepperoni', price: 2.00, isAvailable: true },
              { id: 'add_2', name: 'Mushrooms', price: 1.50, isAvailable: true },
              { id: 'add_3', name: 'Extra Cheese', price: 2.50, isAvailable: true },
              { id: 'add_4', name: 'Truffle Oil', price: 3.00, isAvailable: true },
            ],
          },
        ],
      },
      {
        id: 'food_2',
        restaurantId: 'res_1',
        name: 'Truffle Mushroom Pizza',
        description: 'Wild forest mushrooms, white truffle oil, fresh rosemary, and creamy fontina.',
        price: 18.50,
        imageUrl: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isEgg: false,
        isNonVeg: false,
        isAvailable: true,
        rating: 4.7,
      },
    ],
  },
  {
    id: 'res_2',
    name: 'Burger & Co.',
    description: 'Juicy craft burgers cooked to order with signature hand-cut fries.',
    address: '156 Ludlow St, New York, NY 10002',
    latitude: 40.7201,
    longitude: -73.9877,
    logoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=150&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    phoneNumber: '+1 (555) 345-6789',
    rating: 4.6,
    reviewCount: 512,
    isFeatured: true,
    deliveryRadiusKm: 3.5,
    minOrderAmount: 10.00,
    baseDeliveryFee: 1.99,
    prepTimeRange: '20-30 min',
    categories: ['Burgers', 'American'],
    distanceKm: 1.5,
    promoTag: 'Free Delivery',
    foodItems: [
      {
        id: 'food_3',
        restaurantId: 'res_2',
        name: 'Classic Cheeseburger',
        description: 'Prime Angus beef patty, cheddar, lettuce, tomato, pickles, and house sauce on brioche.',
        price: 12.99,
        imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80',
        isVeg: false,
        isEgg: false,
        isNonVeg: true,
        isAvailable: true,
        rating: 4.8,
        variants: [
          { id: 'v_3', name: 'Single Patty', price: 12.99, isAvailable: true },
          { id: 'v_4', name: 'Double Patty', price: 15.99, isAvailable: true },
        ],
        addonGroups: [
          {
            id: 'ag_2',
            name: 'Add-ons',
            minSelections: 0,
            maxSelections: 3,
            isRequired: false,
            items: [
              { id: 'add_5', name: 'Crispy Bacon', price: 2.00, isAvailable: true },
              { id: 'add_6', name: 'Fried Egg', price: 1.50, isAvailable: true },
              { id: 'add_7', name: 'Avocado', price: 2.00, isAvailable: true },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'res_3',
    name: 'Sushi Zen',
    description: 'Fresh sushi, sashimi, and classic Japanese entrees.',
    address: '202 Allen St, New York, NY 10002',
    latitude: 40.7218,
    longitude: -73.9895,
    logoUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=150&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    phoneNumber: '+1 (555) 456-7890',
    rating: 4.9,
    reviewCount: 1280,
    isFeatured: true,
    deliveryRadiusKm: 5.0,
    minOrderAmount: 25.00,
    baseDeliveryFee: 0.00,
    prepTimeRange: '20-30 min',
    categories: ['Sushi', 'Asian', 'Japanese'],
    distanceKm: 2.4,
    promoTag: '$5 Off on $30+',
    foodItems: [
      {
        id: 'food_4',
        restaurantId: 'res_3',
        name: 'Signature Sushi Platter',
        description: 'Chef\'s selection of 10 pieces of premium nigiri and a spicy tuna roll.',
        price: 28.00,
        imageUrl: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=400&q=80',
        isVeg: false,
        isEgg: false,
        isNonVeg: true,
        isAvailable: true,
        rating: 4.9,
      },
    ],
  },
  {
    id: 'res_4',
    name: 'Fresh Garden Salads',
    description: 'Organic greens, custom toppings, and made-from-scratch dressings.',
    address: '42 Delancey St, New York, NY 10002',
    latitude: 40.7195,
    longitude: -73.9888,
    logoUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=150&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    phoneNumber: '+1 (555) 567-8901',
    rating: 4.4,
    reviewCount: 98,
    isFeatured: false,
    deliveryRadiusKm: 3.0,
    minOrderAmount: 8.00,
    baseDeliveryFee: 3.99,
    prepTimeRange: '10-18 min',
    categories: ['Salads', 'Healthy'],
    distanceKm: 0.5,
    promoTag: 'Save $2 on Greens',
    foodItems: [
      {
        id: 'food_5',
        restaurantId: 'res_4',
        name: 'Avocado Caesar Salad',
        description: 'Crisp romaine, avocado slices, sourdough croutons, shaved parmesan, caesar dressing.',
        price: 11.50,
        imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isEgg: true,
        isNonVeg: false,
        isAvailable: true,
        rating: 4.5,
      },
    ],
  },
  {
    id: 'res_5',
    name: 'Sweet Retreat Bakery',
    description: 'Freshly baked pastries, artisan cupcakes, and custom desserts.',
    address: '95 Clinton St, New York, NY 10002',
    latitude: 40.7188,
    longitude: -73.9855,
    logoUrl: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=150&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=800&q=80',
    phoneNumber: '+1 (555) 678-9012',
    rating: 4.7,
    reviewCount: 456,
    isFeatured: false,
    deliveryRadiusKm: 5.0,
    minOrderAmount: 12.00,
    baseDeliveryFee: 1.49,
    prepTimeRange: '15-22 min',
    categories: ['Desserts', 'Bakery'],
    distanceKm: 3.1,
    promoTag: 'Free Cookie on $15+',
    foodItems: [
      {
        id: 'food_6',
        restaurantId: 'res_5',
        name: 'Red Velvet Cupcake',
        description: 'Fluffy red velvet sponge topped with rich, traditional cream cheese frosting.',
        price: 3.75,
        imageUrl: 'https://images.unsplash.com/photo-1614707267537-b85acf00c4b8?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isEgg: true,
        isNonVeg: false,
        isAvailable: true,
        rating: 4.8,
      },
    ],
  },
  {
    id: 'res_6',
    name: 'El Taco Loco',
    description: 'Authentic street tacos, burritos, and fresh guacamole.',
    address: '110 Stanton St, New York, NY 10002',
    latitude: 40.7222,
    longitude: -73.9868,
    logoUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=150&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    phoneNumber: '+1 (555) 789-0123',
    rating: 4.5,
    reviewCount: 220,
    isFeatured: true,
    deliveryRadiusKm: 4.0,
    minOrderAmount: 10.00,
    baseDeliveryFee: 0.00,
    prepTimeRange: '12-20 min',
    categories: ['Mexican', 'Tacos'],
    distanceKm: 1.1,
    promoTag: 'Spend $15 Save $3',
    foodItems: [
      {
        id: 'food_7',
        restaurantId: 'res_6',
        name: 'Carnitas Taco Platter',
        description: 'Three corn tortillas loaded with slow-roasted pork, onions, cilantro, and fresh lime.',
        price: 9.99,
        imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=400&q=80',
        isVeg: false,
        isEgg: false,
        isNonVeg: true,
        isAvailable: true,
        rating: 4.6,
      },
    ],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord_1',
    restaurant: {
      id: 'res_1',
      name: 'Tavern & Pizzeria',
      logoUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=150&q=80',
    },
    items: [
      {
        name: 'Margherita Pizza',
        price: 14.99,
        quantity: 1,
        variantName: 'Personal 10"',
        addons: ['Pepperoni'],
      },
    ],
    status: 'DELIVERED',
    subtotal: 16.99,
    deliveryFee: 2.99,
    taxAmount: 1.50,
    totalAmount: 21.48,
    createdAt: '2026-07-02T12:00:00Z',
  },
  {
    id: 'ord_2',
    restaurant: {
      id: 'res_2',
      name: 'Burger & Co.',
      logoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=150&q=80',
    },
    items: [
      {
        name: 'Classic Cheeseburger',
        price: 12.99,
        quantity: 2,
        variantName: 'Double Patty',
        addons: ['Crispy Bacon'],
      },
    ],
    status: 'PREPARING',
    subtotal: 35.98,
    deliveryFee: 1.99,
    taxAmount: 3.20,
    totalAmount: 41.17,
    createdAt: '2026-07-02T18:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'nt_1',
    title: 'Order Delivered!',
    body: 'Your order from Tavern & Pizzeria has been delivered. Enjoy!',
    type: 'ORDER_STATUS',
    createdAt: '10 min ago',
    isRead: false,
  },
  {
    id: 'nt_2',
    title: '50% Off Special Promo',
    body: 'Use coupon code EATS50 to get 50% off on your next order.',
    type: 'PROMO',
    createdAt: '2 hours ago',
    isRead: true,
  },
];
